/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsAutoAdapter;

import org.junit.Test;

import motores.*;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testMotorComun() {
        Motor m = new MotorComun();
        assertTrue("Encendiendo Motor Comun".equals(m.encender()));
        assertTrue("Acelerando Motor Comun".equals(m.acelerar()));
        assertTrue("Apagando Motor Comun".equals(m.apagar()));
    }

    @Test public void testMotorEconomico() {
        Motor m = new MotorEconomico();
        assertTrue("Encendiendo Motor Economico".equals(m.encender()));
        assertTrue("Acelerando Motor Economico".equals(m.acelerar()));
        assertTrue("Apagando Motor Economico".equals(m.apagar()));
    }

    @Test public void testMotorElectrico() {
        Motor m = new MotorElectricoAdapter();
        assertTrue("Conectando y Activando Motor Electrico".equals(m.encender()));
        assertTrue("Aumentando Velocidad Motor Electrico".equals(m.acelerar()));
        assertTrue("Deteniendo Motor Electrico".equals(m.apagar()));
    }

    @Test public void testMotorHibrido() {
        Motor m = new MotorHibridoAdapter();
        assertTrue("Encendiendo Motor Hibrido".equals(m.encender()));
        assertTrue("Acelerando Motor Hibrido".equals(m.acelerar()));
        assertTrue("Deteniendo Motor Hibrido".equals(m.apagar()));
    }
}